// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezrpgnmfjcgrmabadwvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6cnBnbm1mamNncm1hYmFkd3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTUzNjYsImV4cCI6MjA2NDM5MTM2Nn0.QETDX9amXZFJ9t4dc7JmcN72L4XX8VUHnWqPXSjIvQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);